#! /usr/bin/env bash

#  __  __                        _
# |  \/  |                      | |
# | \  / | __ _ _ __  _   _  ___| |
# | |\/| |/ _` | '_ \| | | |/ _ \ |
# | |  | | (_| | | | | |_| |  __/ |
# |_|  |_|\__,_|_| |_|\__,_|\___|_|

# Usage: manuel [task]


# -- # -- # -- # -- # -- # -- # -- #
# utility functions
# -- #
function manuel_usage {
  echo -e "  __  __                        _  "
  echo -e " |  \/  |                      | | "
  echo -e " | \  / | __ _ _ __  _   _  ___| | "
  echo -e " | |\/| |/ _\` | '_ \| | | |/ _ \ | "
  echo -e " | |  | | (_| | | | | |_| |  __/ | "
  echo -e " |_|  |_|\__,_|_| |_|\__,_|\___|_| "
  echo -e "\n  Usage: manuel [task] [params]"
  exit 1
}


# -- # -- # -- # -- # -- # -- # -- #
# built-in tasks
# -- #
function init {
  if [[ -f manuelfile ]]; then
    echo ">> manuelfile already exists, nothing to do"
  else
    echo ">> Creating new manuelfile in `pwd`"
    echo '#! /usr/bin/env bash

function hello {
  echo ">> Hello from manuel!"
}
' >> manuelfile
  fi
}


# -- # -- # -- # -- # -- # -- # -- #
# main function
# -- #
function manuel_main {
  if [[ $# = 0 ]]; then
    manuel_usage
  fi
  # main
  if [[ "$1" == "init" ]]; then
    init
  else
    if [[ -f manuelfile ]]; then
      source manuelfile
      eval $@
    else
      echo -e "No manuelfile found, exiting"
      exit 1
    fi
  fi
  exit 0
}


manuel_main $@
