#! /usr/bin/env bash

#  __  __                        _
# |  \/  |                      | |
# | \  / | __ _ _ __  _   _  ___| |
# | |\/| |/ _` | '_ \| | | |/ _ \ |
# | |  | | (_| | | | | |_| |  __/ |
# |_|  |_|\__,_|_| |_|\__,_|\___|_|

# Usage: manuel [task]


# -- # -- # -- # -- # -- # -- # -- #
# utility functions
# -- #
function manuel_usage {
  echo -e "  __  __                        _  "
  echo -e " |  \/  |                      | | "
  echo -e " | \  / | __ _ _ __  _   _  ___| | "
  echo -e " | |\/| |/ _\` | '_ \| | | |/ _ \ | "
  echo -e " | |  | | (_| | | | | |_| |  __/ | "
  echo -e " |_|  |_|\__,_|_| |_|\__,_|\___|_| "
  echo -e "\n  Usage: manuel [task] [params]"
  exit 1
}


# -- # -- # -- # -- # -- # -- # -- #
# built-in tasks
# -- #
function init {
  if [[ -f manuelfile ]]; then
    echo ">> manuelfile already exists, nothing to do"
    exit 0
  else
    echo ">> Creating new manuelfile in `pwd`"
    echo '#! /usr/bin/env bash

# run this task with: $ manuel hello
function hello {
  echo ">> Hello from manuel!"
}
' >> manuelfile
    exit 0
  fi
}

function manuel_watch {
  target_dir=`readlink -f $1` # a directory to watch for changes in
  actions=$2          # associative array of regex=>command

  echo -e ">> Watching $target_directory"

  # set up watches
  inotifywait -mrq $target_dir --event=CREATE,MOVE,DELETE,ATTRIB | while read LINE
  do
    IFS=' ' read -a event <<< "$LINE"
    directory=${event[0]}
    action=${event[1]}
    target=${event[2]}

    # check if the event target matches any patterns in actions map
    for k in ${!actions[@]}
    do
      v=${actions[$k]}
      if [[ $target =~ $k ]]; then
        echo -e "\n>> Change event $action detected for $target ..."
        eval $v
      fi
    done
  done
}


# -- # -- # -- # -- # -- # -- # -- #
# main function
# -- #
function manuel_main {

  if [[ $# = 0 ]]; then
    manuel_usage
  fi

  if [[ "$1" == "init" ]]; then
    init
  fi

  if [[ -f manuelfile ]]; then
    source manuelfile
    eval $@
    exit 0
  else
    echo -e "No manuelfile found, exiting"
    exit 1
  fi

  exit 0
}


manuel_main $@
